### ISSUE TITLE
im geting this error and idk

### ISSUE THREAD

**Issue by keganpowers34** [jep-a/emm#23]
[ERROR] gamemodes/emm/gamemode/hud/indicators.cl.lua:10: attempt to index global 'SettingsService' (a nil value)
  1. Visible - gamemodes/emm/gamemode/hud/indicators.cl.lua:10
   2. v - gamemodes/emm/gamemode/hud/indicators.cl.lua:319
    3. Run - lua/includes/modules/hook.lua:84
     4. v - gamemodes/emm/gamemode/hud/hud.cl.lua:189
      5. unknown - lua/includes/modules/hook.lua:84

**Comment by Escapist-** [comment]
This is entirely ambiguous. You didn't tell us what happened as a consequence of the error or even what you were doing at the time. We aren't detectives; if you can't provide critical information about the error we can't figure out what's wrong. 

With that said, I'm closing this for now until someone replicates the bug and can provide more information.
