### ISSUE TITLE
Outdated

### ISSUE THREAD

**Issue by Zachac** [jep-a/emm#49]
Yes, I'd like to report an issue. It looks like this was written for GMod, when S&Box is now open for beta testing. 
https://www.youtube.com/watch?v=BAA9tUI181o

I think someone should really update for S&Box.

I implemented a rudimentary source/parkour physics in only 6 hours: https://www.youtube.com/watch?v=BAA9tUI181o
So it should be possible now, I think.

I dunno how else to contact you guys, cause I lost the discord link, but if you wanna start a project for S&Box, let me know. (This is Parity/Sparky btw)

**Comment by Pivius** [comment]
https://discord.gg/WBSaGn8B
Join and at message arkade or Developers :)
